blog/posts/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


def strip_filter(x): return x.rstrip() if x else None


class PostForm(Form):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[
                            DataRequired()], filters=[strip_filter])
    submit = SubmitField('Post')

blog/main/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from blog.main.forms import MemberForm
from blog.models import Post
import json
import requests

main = Blueprint("main", __name__)


def send_to_google(firstname, lastname, email, phone, usn, branch, semester):
    payload = {
        "firstname": firstname,
        "lastname": lastname,
        "email": email,
        "phone": phone,
        "usn": usn,
        "branch": branch,
        "semester": semester,
    }
    print(payload)
    url = "https://script.google.com/macros/s/AKfycbza4Lx4a1AO9Ea48C57OoqTGYq2Asqf0ipYG0R5-N8cLj2Fwpc/exec"
    requests.post(url, params=payload)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/member", methods=["GET", "POST"])
def member():
    form = MemberForm()
    if request.method == "POST" and form.validate_on_submit():
        firstname = form.firstname.data
        lastname = form.lastname.data
        email = form.email.data
        phone = form.phone.data
        usn = form.usn.data
        branch = form.branch.data
        semester = form.semester.data

        send_to_google(firstname, lastname, email, phone, usn, branch, semester)
        flash(
            " Dear {}, your registration was successful!".format(
                form.firstname.data + " " + form.lastname.data
            ),
            "success",
        )
        return redirect(url_for("main.member"))
    return render_template("member.html", form=form)


@main.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template("home.html", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html")

blog/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from blog import db
from blog.models import Post, PostLike
from blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', form=form, legend="New Post")


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been update!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', form=form, legend="Update Post")


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted', 'success')
    return redirect(url_for('main.home'))


@posts.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = Post.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)

blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from blog import db
from blog.models import User, Post
from blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from blog.users.utils import send_reset_email
from werkzeug.security import generate_password_hash, check_password_hash

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password, is_admin=False)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)


@users.route('/admIn_regIster', methods=['GET', 'POST'])
def admin_register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password, is_admin=True)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('admin_register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('login unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', form=form)


@users.route('/admIn_logIn', methods=['GET', 'POST'])
def admin_login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            if not user.is_admin:
                flash('You are not an admin!', 'danger')
                return render_template('admin_login.html', form=form)
            else:
                login_user(user, remember=form.remember.data)
                flash('You are successfully logged in!', 'success')
                return render_template('admin_login.html', form=form)
        else:
            flash('login unsuccessful. Please check email and password', 'danger')
    return render_template('admin_login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or the session is expired', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in!', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

blog/templates/about.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div" ></div>
<div class="content-section">
  <h2 class="text-center">About page</h2>
  <p class="article-content">
    UCSP is a unique and innovative initiative from the department of ECE, NIE
    to bring research to UG students in a revolutionary way. Aiming at achieving
    this, here we introduce the blog. The main focus of this will be exploring
    new domains, encouraging technical writing as well as information exchange.
    This platform can be used if you need clarifications regarding any technical
    concept, if you want to share any new idea or if you have any
    suggestions/doubts related to our events or projects. We hope you make the
    best of it. Happy reading!
  </p>
</div>
{% endblock %}

blog/templates/account.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div" ></div>

<div class="register-content-section">
  <div class="media">
    <!-- <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <p class="text" style="color: #fff">{{ current_user.email }}</p>
    </div> -->
  </div>
  <!-- FORM HERE -->
  <form method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Account</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }} {% if
        form.username.errors %} {{ form.username(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.username(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-light") }}
    </div>
  </form>
</div>
{% endblock %}

blog/templates/admin_login.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div" ></div>
<div class="content-section">
  <form method="POST" action="{{ url_for('users.admin_login') }}">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login</legend>

      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }} {{
        form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-dark") }}
      <small class="text-muted ml-2">
        <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
      </small>
    </div>
  </form>
</div>
<!-- <div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up</a>
    </small>
</div> -->
{% endblock content %}

blog/templates/admin_register.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div" ></div>
<div class="login-content-section">
  <form method="POST" action="{{ url_for('users.admin_register') }}">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Join Today</legend>
      <div class="form-group">
        {{ form.username.label(class="form-control-label") }} {% if
        form.username.errors %} {{ form.username(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.username.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.username(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label(class="form-control-label") }} {% if
        form.confirm_password.errors %} {{
        form.confirm_password(class="form-control form-control-lg is-invalid")
        }}
        <div class="invalid-feedback">
          {% for error in form.confirm_password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.confirm_password(class="form-control
        form-control-lg") }} {% endif %}
      </div>
    </fieldset>
    <div class="form-group">
      {{ form.submit(class="btn btn-outline-dark") }}
    </div>
  </form>
</div>
<div class="border-top pt-3">
  <small class="text-muted" style="color: #fff">
    Already Have An Account?
    <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
  </small>
</div>
{% endblock content %}

blog/templates/home.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div"></div>
{% for post in posts.items %}
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a
        href="{{ url_for('users.user_posts', username = post.author.username) }}"
        class="mr-2"
        style="
          text-decoration: none;
          color: #fff;
          font-family: 'Literata', serif;
        "
        >{{ post.author.username }}</a
      >
      <small class="">{{post.date_posted.strftime('%d-%m-%Y')}}</small>
    </div>
    <h2>
      <a
        href="{{ url_for('posts.post', post_id=post.id) }}"
        class="article-title"
        >{{post.title}}</a
      >
    </h2>
    <p class="article-content">{{post.content}}</p>
    <div class="like">
      {% if current_user.is_authenticated %}
      <span style="font-size: 1.5em">{{ post.likes.count() }}</span>
      {% if current_user.has_liked_post(post) %}
      <a
        href="{{ url_for('posts.like_action', post_id=post.id, action='unlike') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #f1e0cb !important"
          aria-hidden="true"
        ></i
      ></a>
      {% else %}
      <a
        href="{{ url_for('posts.like_action', post_id = post.id, action='like') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #232323 !important"
          aria-hidden="true"
        ></i
      ></a>
      {% endif %} {% else %} {{ post.likes.count() }}
      <a
        href="{{ url_for('posts.like_action', post_id = post.id, action='like') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #232323 !important"
          aria-hidden="true"
        ></i
      ></a>
      {% endif %}
    </div>
  </div>
</article>
{% endfor %} <br />
<div class="bottom_button">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1,
  right_current=2) %} {% if page_num %} {% if posts.page == page_num %}
  <a
    class="btn btn-outline-dark mb-4"
    href="{{ url_for('main.home', page=page_num) }}"
    >{{ page_num }}</a
  >
  {% else %}
  <a
    class="btn btn-outline-dark mb-4"
    href="{{ url_for('main.home', page=page_num) }}"
    >{{ page_num }}</a
  >
  {% endif %} {% else %} ... {% endif %} {% endfor %}
</div>
{% endblock %}

blog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{url_for('static',filename = 'fontawesome-free-5.1.0-web/css/all.css')}}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <!-- fontawesome cdn -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>UCSP | Blog</title>
  <link rel="shortcut icon" href="{{url_for('static', filename= 'img/favicon.ico')}}" type="image/x-icon" />
</head>

<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark  fixed-top" id="nav1">
      <a class="navbar-brand" href="{{url_for('main.index')}}"><img src="{{url_for('static', filename= 'img/ucsp.png')}}" width="80" alt="UCSP"/></a>
      <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.home')}}">Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.index', _anchor='about')}}">About</a>
          </li>
          
          {% if current_user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('posts.new_post')}}">New Post</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('users.account')}}">Account</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('users.logout')}}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>
          </li>
          <!-- <li class="nav-item active">
            <a class="nav-item nav-link" href="{{ url_for('users.register')}}"><i class="fas fa-home"></i>&nbsp;Register</a>
          </li> -->
          {% endif %}
          
      </div>
    </nav>
  </header>

  <main role="main" class="container">
    <div class="row">
      <div class="col-md-10">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{category}}">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          {{message}}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <!-- <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
          </p>
        </div>
      </div> -->
      </div>
  </main>

</body>

</html>

blog/templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div" ></div>
<div class="login-content-section">
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Login</legend>

      <div class="form-group">
        {{ form.email.label(class="form-control-label") }} {% if
        form.email.errors %} {{ form.email(class="form-control form-control-sm
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class="form-control form-control-sm") }} {%
        endif %}
      </div>

      <div class="form-group">
        {{ form.password.label(class="form-control-label") }} {% if
        form.password.errors %} {{ form.password(class="form-control
        form-control-sm is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class="form-control form-control-sm") }} {%
        endif %}
      </div>
      <div class="form-check">
        {{ form.remember(class="form-check-input") }} {{
        form.remember.label(class="form-check-label") }}
      </div>
    </fieldset>
    <div class="form-group submit_button">
      {{ form.submit(class="btn btn-outline-light") }}
      <small class="ml-2">
        <a href="{{ url_for('users.reset_request') }}" style="color: #fff"
          >Forgot password?</a
        >
      </small>
    </div>
  </form>
</div>
<div>
  <!-- <small style="color: #efeffe">
    Need An Account?
    <a class="ml-2" href="{{ url_for('users.register') }}" style="color: #fff"
      >Sign up</a
    >
  </small> -->
</div>
{% endblock content %}

blog/templates/post.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div" ></div>
<article class="media login-content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a
        href="{{ url_for('users.user_posts', username = post.author.username) }}"
        class="mr-2"
        style="
          text-decoration: none;
          color: #ffffff;
          font-family: 'Literata', serif;
        "
        >{{ post.author.username }}</a
      >
      <small class="text-muted">{{post.date_posted.strftime('%d-%m-%Y')}}</small
      ><br />
      {% if post.author == current_user %}
      <div>
        <a
          class="btn btn-success btn-sm m-1"
          href="{{ url_for('posts.update_post', post_id=post.id) }}"
          >Update
        </a>
        <button
          type="button"
          class="btn btn-danger btn-sm mt-1 mb-1"
          data-toggle="modal"
          data-target="#deleteModal"
        >
          Delete
        </button>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{post.title}}</h2>
    <p class="article-content">{{post.content}}</p>
    <div class="like">
      {% if current_user.is_authenticated %}
      <span style="font-size: 1.5em">{{ post.likes.count() }}</span>
      {% if current_user.has_liked_post(post) %}
      <a
        href="{{ url_for('posts.like_action', post_id=post.id, action='unlike') }}"
        ><i
          class="fa fa-thumbs-up"
          style="color: #f1e0cb !important; font-size: 2em"
          aria-hidden="true"
        ></i
      ></a>
      {% else %}
      <a
        href="{{ url_for('posts.like_action', post_id = post.id, action='like') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #232323 !important"
          aria-hidden="true"
        ></i
      ></a>
      {% endif %} {% else %} {{ post.likes.count() }}
      <a
        href="{{ url_for('posts.like_action', post_id = post.id, action='like') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #232323 !important"
          aria-hidden="true"
        ></i
      ></a>
      {% endif %}
    </div>
  </div>
</article>
<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <form
          action="{{url_for('posts.delete_post', post_id=post.id)}}"
          method="POST"
        >
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/user_posts.html
{% extends "layout.html" %} {% block content %}
<div class="empty_div"></div>
{% for post in posts.items %}
<article class="media login-content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a
        href="{{ url_for('users.user_posts', username = post.author.username) }}"
        class="mr-2"
        style="
          text-decoration: none;
          color: #fff;
          font-family: 'Literata', serif;
        "
        >{{ post.author.username }}</a
      >
      <small class="text-muted"
        >{{post.date_posted.strftime('%d-%m-%Y')}}</small
      >
    </div>
    <h2>
      <a
        href="{{ url_for('posts.post', post_id=post.id) }}"
        class="article-title"
        >{{post.title}}</a
      >
    </h2>
    <p class="article-content">{{post.content}}</p>
    <div class="like">
      {% if current_user.is_authenticated %}
      <span style="font-size: 1.5em">{{ post.likes.count() }}</span>
      {% if current_user.has_liked_post(post) %}
      <a
        href="{{ url_for('posts.like_action', post_id=post.id, action='unlike') }}"
        ><i
          class="fa fa-thumbs-up"
          style="color: #f1e0cb !important; font-size: 2em"
          aria-hidden="true"
        ></i
      ></a>
      {% else %}
      <a
        href="{{ url_for('posts.like_action', post_id = post.id, action='like') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #232323"
          aria-hidden="true"
        ></i
      ></a>
      {% endif %} {% else %} {{ post.likes.count() }}
      <a
        href="{{ url_for('posts.like_action', post_id = post.id, action='like') }}"
        ><i
          class="fa fa-thumbs-up"
          style="font-size: 2em; color: #232323"
          aria-hidden="true"
        ></i
      ></a>
      {% endif %}
    </div>
  </div>
  <br />
</article>
{% endfor %}
<div class="bottom_button">
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1,
  right_current=2) %} {% if page_num %} {% if posts.page == page_num %}
  <a
    class="btn btn-outline-dark mb-4"
    href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"
    >{{ page_num }}</a
  >
  {% else %}
  <a
    class="btn btn-outline-dark mb-4"
    href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"
    >{{ page_num }}</a
  >
  {% endif %} {% else %} ... {% endif %} {% endfor %}
</div>
{% endblock %}